name: "HACS: Push action"
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ludeeus/hacs-actions@master
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          modules: 
            - "IssueGreeter"
      - uses: ludeeus/hacs-actions@master
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          modules: 
            - "IssueGreeter"
            - HacktoberFest
