name: "Test action"
on:
  pull_request:
    types: [labeled, opened, synchronize, reopened, closed]
  issues:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: ludeeus/hacs-actions@master
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
