name: "HACS: Push action"
on: issues

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: ludeeus/hacs-actions@master
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        action: "Test"
