name: "Test typescript-action"
on: ["push"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: ludeeus/hacs-actions@master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
